// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlUiL8FxQbKhOA4S3Of5goJTHphKpFGAI',
    appId: '1:732492746255:web:8cd0f68c15c63031a35d7a',
    messagingSenderId: '732492746255',
    projectId: 'rwh-app-9e78f',
    authDomain: 'rwh-app-9e78f.firebaseapp.com',
    storageBucket: 'rwh-app-9e78f.firebasestorage.app',
    measurementId: 'G-C4225D2WWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0d_xUzBc8mfi_GNW92Haa7XUGFw6IvH4',
    appId: '1:732492746255:android:64927423ca0be92aa35d7a',
    messagingSenderId: '732492746255',
    projectId: 'rwh-app-9e78f',
    storageBucket: 'rwh-app-9e78f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTZuXcxetZeOsvbmxzY3V9wBZ-5UQ-2d0',
    appId: '1:732492746255:ios:da4412f1c6f69274a35d7a',
    messagingSenderId: '732492746255',
    projectId: 'rwh-app-9e78f',
    storageBucket: 'rwh-app-9e78f.firebasestorage.app',
    iosBundleId: 'com.example.rwhApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTZuXcxetZeOsvbmxzY3V9wBZ-5UQ-2d0',
    appId: '1:732492746255:ios:da4412f1c6f69274a35d7a',
    messagingSenderId: '732492746255',
    projectId: 'rwh-app-9e78f',
    storageBucket: 'rwh-app-9e78f.firebasestorage.app',
    iosBundleId: 'com.example.rwhApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlUiL8FxQbKhOA4S3Of5goJTHphKpFGAI',
    appId: '1:732492746255:web:c8a44eb6198efd2aa35d7a',
    messagingSenderId: '732492746255',
    projectId: 'rwh-app-9e78f',
    authDomain: 'rwh-app-9e78f.firebaseapp.com',
    storageBucket: 'rwh-app-9e78f.firebasestorage.app',
    measurementId: 'G-Q1VBLQQ2MV',
  );
}
