// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRRYMcvKG9qVkkt1BKzRG06_GRyLRebGM',
    appId: '1:426294308064:web:beb87ba7ab917c8dec7485',
    messagingSenderId: '426294308064',
    projectId: 'sih-rwh',
    authDomain: 'sih-rwh.firebaseapp.com',
    storageBucket: 'sih-rwh.firebasestorage.app',
    measurementId: 'G-4XQRPP0J1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuy8bMPndx2i8M9d4PVYP6Yfq2DF26Hzk',
    appId: '1:426294308064:android:de221f6e1cdf5463ec7485',
    messagingSenderId: '426294308064',
    projectId: 'sih-rwh',
    storageBucket: 'sih-rwh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADuxcN20oxsZFZjq7dSXYcCNherkNH2NU',
    appId: '1:426294308064:ios:366caf29aecb4f2fec7485',
    messagingSenderId: '426294308064',
    projectId: 'sih-rwh',
    storageBucket: 'sih-rwh.firebasestorage.app',
    iosBundleId: 'com.example.rwhApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADuxcN20oxsZFZjq7dSXYcCNherkNH2NU',
    appId: '1:426294308064:ios:366caf29aecb4f2fec7485',
    messagingSenderId: '426294308064',
    projectId: 'sih-rwh',
    storageBucket: 'sih-rwh.firebasestorage.app',
    iosBundleId: 'com.example.rwhApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRRYMcvKG9qVkkt1BKzRG06_GRyLRebGM',
    appId: '1:426294308064:web:853ef97e10611fe8ec7485',
    messagingSenderId: '426294308064',
    projectId: 'sih-rwh',
    authDomain: 'sih-rwh.firebaseapp.com',
    storageBucket: 'sih-rwh.firebasestorage.app',
    measurementId: 'G-07W805EX6N',
  );

}